### ISSUE TITLE
 nothing happens 

### ISSUE THREAD

**Issue by 11111000000** [webpack/analyse#10]
When I select file stats.json to upload - nothing happens - firefox, chromium

**Comment by 11111000000** [comment]
I solve this, but we need to show errors

**Comment by simonsmith** [comment]
How did you solve this? Having the same issue.

**Comment by jschaf** [comment]
What was the solution?  I have the same issue.

**Comment by simonsmith** [comment]
Check the console. For me it was a JSON parsing error that was failing silently.

**Comment by 11111000000** [comment]
@jschaf : maybe, your `webpack.config` contains some `console.log` or other output
