### ISSUE TITLE
Allow for children builds

### ISSUE THREAD

**Issue by zrosenbauer** [webpack/analyse#15]
We are running into issues as we have seperate builds for client and server. We can do one of two things seperate them completely OR allow the load function in app.js to account for stats.children array. This might take some refactoring BUT with Hacktoberfest coming up might be something worthy of attacking. 

for reference our webpack.config.js:
```
module.exports = exports = [
  require('./configs/webpack/client'),
  require('./configs/webpack/server')
];
```
This might be a bit more of an enhancement vs. a bug.

**Comment by a-r-d** [comment]
@zrosenbauer I think this PR I just merged fixes your issue:
https://github.com/webpack/analyse/pull/21
