### ISSUE TITLE
"TypeError: t.chunks is undefined" console error when uploading my file

### ISSUE THREAD

**Issue by doberkofler** [webpack/analyse#25]
When uploading my stats.json file, I get a `TypeError: t.chunks is undefined` error.
[stats.json.gz](https://github.com/webpack/analyse/files/315522/stats.json.gz)

It would actually be a nice addition, to show any error message in the file upload dialog.

**Comment by mmajko** [comment]
+1, same problem here

**Comment by wegry** [comment]
@doberkofler @mmajko are you using Webpack 2?

**Comment by a-r-d** [comment]
@doberkofler I'll merge the error message feature in you would like to make a pull request.

**Comment by a-r-d** [comment]
@doberkofler closing this, I just put in a fix for this particular error
