### ISSUE TITLE
Error on analyze

### ISSUE THREAD

**Issue by nicksrandall** [webpack/analyse#27]
I'm using webpack 2 and when  I upload my file, I get an error because my stats.json file doesn't have an assets or chunks property.

There error is here: https://github.com/webpack/analyse/blob/master/app/app.js#L6

**Comment by Rosenblad** [comment]
I'm getting the following error in my console.

Uncaught TypeError: Cannot read property 'sort' of undefined

**Comment by a-r-d** [comment]
@nicksrandall or @Rosenblad can you provide an example stats file, I'll work on a fix if I can see what you have

**Comment by a-r-d** [comment]
@nicksrandall actually I just put in a fix for this if you could please try it again and let me know.

**Comment by urbanhusky** [comment]
I'm also getting 
```
Uncaught TypeError: Cannot read property 'sort' of undefined
    at r (web.js:1)
    at Object.e.load (web.js:1)
    at FileReader.e.onload (8.568a26e….js:1)
```

**Comment by a-r-d** [comment]
@urbanhusky  would you be able to provide the JSON file you are using to help me debug it?

**Comment by urbanhusky** [comment]
**I found the error:** my json file was malformed.
Aside from having console output in the beginning (which I deleted), the structure is also more deeply nested than expected:

```
----> Production

[at-loader] Using typescript@2.2.2 from typescript and "tsconfig.json" from C:\work\sf-metadata-management\src\Senseforce.Application.Web/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 1.588 sec.
{
  "errors": [],
  "warnings": [],
  "version": "2.3.2",
  "hash": "ed980083c66ffe11081e",
  "children": [
    // actual stats are defined in here
  ]
}
```

My solution was to remove this outer layer (and the non-json in the beginning).

**Comment by a-r-d** [comment]
@urbanhusky OK cool, closing this.
