### ISSUE TITLE
Deploy most recent version to website

### ISSUE THREAD

**Issue by jakepusateri** [webpack/analyse#31]
The deployed version at http://webpack.github.io/analyse/ is older than the code. I know at least it does not pop open a modal for multi-compiles as added in this commit: https://github.com/webpack/analyse/commit/20992e5a65775b5e8238e25f627cfaa1d548aaf6

I can run locally and it works, but it would be better the latest version if it were on the deployed website.

**Comment by peter-hartmann** [comment]
+1
It's broken, I'm able to select a file and after that nothing happens.  I tried different browsers.

**Comment by AndrewCraswell** [comment]
@peter-hartmann , seems webpack started adding a line of plain text at the beginning of the exported stats.json, and also at the end. After removing those and refreshing the page, I'm able to get the online version to work. Verified on a local build as well.
