### ISSUE TITLE
Sort by size functionality on #modules, #chunk and #assets

### ISSUE THREAD

**Issue by arypurnomoz** [webpack/analyse#9]
It would be perfect if the table on #modules, #chunk and #assets can be sorted by size.

**Comment by wmertens** [comment]
And there's #16 :)

It would be even nicer if the dependency tree could be shown with total size of all children. Then you could see that the little module you use for blinking pulls in 3MB of JS…

**Comment by a-r-d** [comment]
@arypurnomoz merged: https://github.com/webpack/analyse/pull/16
